# Generated by Django 4.0.3 on 2022-03-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_student', models.CharField(choices=[('FE', 'First Year'), ('SE', 'Second Year'), ('TE', 'Third Year'), ('BE', 'Final Year')], max_length=4)),
                ('division_student', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=4)),
                ('subject', models.CharField(max_length=40)),
                ('lectures_taught', models.IntegerField(max_length=4)),
                ('scoreclaimed', models.IntegerField(max_length=4)),
                ('collpolllink', models.CharField(max_length=150)),
            ],
        ),
    ]
