# Generated by Django 4.0.3 on 2022-03-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_facultymembers_delete_formone'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pron', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('FacultyID', models.CharField(max_length=200)),
                ('nameofInstitute', models.CharField(max_length=200)),
                ('nameofDepartment', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('statelocation', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('joiningdate', models.DateField()),
                ('expyears', models.IntegerField()),
                ('ndyexpyears', models.IntegerField()),
                ('yearofappraisel', models.IntegerField()),
            ],
        ),
    ]
