# Generated by Django 4.0.3 on 2022-03-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_facultyinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('basicprofile', models.CharField(max_length=20)),
                ('FormOne', models.CharField(max_length=20)),
                ('FormTwo', models.CharField(max_length=20)),
                ('FormThree', models.CharField(max_length=20)),
                ('FormFour', models.CharField(max_length=20)),
                ('FormFive', models.CharField(max_length=20)),
                ('FormSix', models.CharField(max_length=20)),
                ('FormSeven', models.CharField(max_length=20)),
                ('FormEight', models.CharField(max_length=20)),
                ('FacultyID', models.CharField(max_length=200)),
                ('NetCoutFormFilled', models.IntegerField()),
            ],
        ),
    ]
