# Generated by Django 4.0.3 on 2022-03-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_formprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('currentclass', models.CharField(max_length=200)),
                ('division', models.CharField(max_length=200)),
                ('subjectname', models.CharField(max_length=200)),
                ('numberoflectures', models.IntegerField()),
                ('scoreclaimedbyfaculty', models.IntegerField()),
                ('collpolllink', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FormTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('currentclass', models.CharField(max_length=200)),
                ('division', models.CharField(max_length=200)),
                ('subjectname', models.CharField(max_length=200)),
                ('numberofstudent', models.IntegerField()),
                ('dateofexam', models.CharField(max_length=200)),
                ('appointedas', models.CharField(max_length=200)),
                ('fclaimedmarks', models.IntegerField()),
            ],
        ),
    ]
