# Generated by Django 2.2.12 on 2022-05-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220513_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='bformprogress',
            name='basicprofile',
            field=models.CharField(default='incomplete', max_length=20),
        ),
    ]
