# Generated by Django 2.2.12 on 2022-05-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_bformprogress_basicprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BformOneA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ptmeet', models.CharField(max_length=200)),
                ('inductionProgram', models.CharField(max_length=200)),
                ('defaulterCoordinator', models.CharField(max_length=200)),
                ('internalExam', models.CharField(max_length=200)),
                ('guestLecture', models.CharField(max_length=200)),
                ('industrialVisit', models.CharField(max_length=200)),
                ('timeTableCoordinator', models.CharField(max_length=200)),
                ('nbaNaacCoordi', models.CharField(max_length=200)),
                ('deptAcademic', models.CharField(max_length=200)),
                ('tpoCordinate', models.CharField(max_length=200)),
                ('fclaimedmarks', models.IntegerField()),
                ('totalmarks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BformOneB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('interviewCoordinator', models.CharField(max_length=200)),
                ('annualEvent', models.CharField(max_length=200)),
                ('admissionProcess', models.CharField(max_length=200)),
                ('ceo', models.CharField(max_length=200)),
                ('guestLecture', models.CharField(max_length=200)),
                ('nbaNaacCoordi', models.CharField(max_length=200)),
                ('tpoCordinate', models.CharField(max_length=200)),
                ('fclaimedmarks', models.IntegerField()),
                ('totalmarks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BformOneC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('mediaPublicity', models.CharField(max_length=200)),
                ('admission', models.CharField(max_length=200)),
                ('socialWelfare', models.CharField(max_length=200)),
                ('fclaimedmarks', models.IntegerField()),
                ('totalmarks', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='bformprogress',
            old_name='FormOne',
            new_name='FormOneA',
        ),
        migrations.AddField(
            model_name='bformprogress',
            name='FormOneB',
            field=models.CharField(default='incomplete', max_length=20),
        ),
        migrations.AddField(
            model_name='bformprogress',
            name='FormOneC',
            field=models.CharField(default='incomplete', max_length=20),
        ),
    ]
