# Generated by Django 2.2.12 on 2022-06-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220521_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bformonea',
            name='defaulterCoordinator',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='bformonea',
            name='deptAcademic',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='bformonea',
            name='guestLecture',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='bformonea',
            name='inductionProgram',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='bformonea',
            name='industrialVisit',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='bformonea',
            name='internalExam',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='bformonea',
            name='nbaNaacCoordi',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='bformonea',
            name='ptmeet',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='bformonea',
            name='timeTableCoordinator',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='bformonea',
            name='tpoCordinate',
            field=models.FileField(upload_to=''),
        ),
    ]
