# Generated by Django 2.2.12 on 2022-06-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20220606_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bformonec',
            name='admission',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='bformonec',
            name='mediaPublicity',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='bformonec',
            name='socialWelfare',
            field=models.FileField(upload_to=''),
        ),
    ]
